//-------------USUARIO-------------
### Listar
GET http://localhost:4321/usuario/listar-usuario

### BuscarPorId
GET http://localhost:4321/usuario/listar-usuario/6091e76c4f18793f5c26a1eb

### Cadastrar Usuario
POST http://localhost:4321/usuario/cadastrar-usuario
Content-Type: application/json

{
    "email": "teste@testa",
    "username": "teste1aaaa",
    "senha": "00201010",
    "favoritos": []
}

### Deletar
DELETE http://localhost:4321/usuario/deletar-usuario/609345a782b7332b04cf8166

### Editar
PUT http://localhost:4321/usuario/editar-usuario/6093468b2e69514f04c97ca1
Content-Type: application/json

{
    "email": "teste@editado",
    "username": "testeEditado",
    "senha": "00201010",
    "favoritos": []
}

### Adicionar a Favoritos
POST http://localhost:4321/usuario/adicionar-favorito/609345ec82b7332b04cf8168/609345a782b7332b04cf8166

### Remover Favoritos
POST http://localhost:4321/usuario/remover-favorito/6091e5e2ac125510bc088f05/6091e7724f18793f5c26a1ec



//------------RECEITA-------------
### Listar
GET http://localhost:4321/receita/listar-receita

### BuscarPorId
GET http://localhost:4321/receita/listar-receita/6091e5e2ac125510bc088f05

### Cadastrar Requisisão correta
POST http://localhost:4321/receita/cadastrar-receita
Content-Type: application/json

{
    "nomeReceita": "teste2",
    "ingrediente": "teste",
    "modoPreparo": "teste",
    "tempoPreparo": 40,
    "rendimento": 5
}

### Cadastrar Requisisão com erro
POST http://localhost:4321/receita/cadastrar-receita
Content-Type: application/json

{
    "nomeReceita": "teste2",
    "ingrediente": "teste2",
    "modoPreparo": "teste2",
    "tempoPreparo": 40,
    "rendimento": 5
}

### Deletar
DELETE http://localhost:4321/receita/deletar-receita/6091e5f5ac125510bc088f06

### Editar
PUT http://localhost:4321/receita/editar-receita/6091e5e2ac125510bc088f05
Content-Type: application/json

{
    "nomeReceita": "testeEditado",
    "ingrediente": "testeEditado",
    "modoPreparo": "testeEditado",
    "tempoPreparo": 40,
    "rendimento": 5
}