//-------------USUARIO-------------
### Listar
GET http://localhost:4321/usuario/listar-usuario

### BuscarPorId
GET http://localhost:4321/usuario/listar-usuario/6093f1ff5075d121b07ffde0

### Cadastrar Usuario
POST http://localhost:4321/usuario/cadastrar-usuario
Content-Type: application/json

{
    "email": "teste@aaaaa",
    "username": "aaaaaa",
    "senha": "00201010",
    "favoritos": []
}

### Deletar
DELETE http://localhost:4321/usuario/deletar-usuario/6093f2495075d121b07ffde1

### Editar
PUT http://localhost:4321/usuario/editar-usuario/6093f1ff5075d121b07ffde0
Content-Type: application/json

{
    "email": "teste@editado",
    "username": "testeEditado",
    "senha": "00201010",
    "favoritos": []
}

### Adicionar a Favoritos
POST http://localhost:4321/usuario/adicionar-favorito/6093f908b39e7c482c899ffd/6093f3455075d121b07ffde3

### Remover Favoritos
POST http://localhost:4321/usuario/remover-favorito/6093f3455075d121b07ffde3/6093f3455075d121b07ffde3



//------------RECEITA-------------
### Listar
GET http://localhost:4321/receita/listar-receita

### BuscarPorId
GET http://localhost:4321/receita/listar-receita/6093f2f25075d121b07ffde2

### Cadastrar Requisisão correta
POST http://localhost:4321/receita/cadastrar-receita
Content-Type: application/json

{
    "nomeReceita": "Feijoada",
    "ingrediente": "teste",
    "modoPreparo": "teste",
    "tempoPreparo": 40,
    "rendimento": 5
}

### Deletar
DELETE http://localhost:4321/receita/deletar-receita/6093f2f25075d121b07ffde2

### Editar
PUT http://localhost:4321/receita/editar-receita/6093f3455075d121b07ffde3
Content-Type: application/json

{
    "nomeReceita": "testeEditado",
    "ingrediente": "testeEditado",
    "modoPreparo": "testeEditado",
    "tempoPreparo": 40,
    "rendimento": 5
}

//------------PAIS-------------
### Listar
GET http://localhost:4321/pais/listar-pais

### BuscarPorId
GET http://localhost:4321/pais/listar-pais/6093f2f25075d121b07ffde2

### Cadastrar Requisisão correta
POST http://localhost:4321/pais/cadastrar-pais
Content-Type: application/json

{
    "nomePais": "EUA",
    "receitas": []
}

### Deletar
DELETE http://localhost:4321/pais/deletar-pais/6093f2f25075d121b07ffde2

### Editar
PUT http://localhost:4321/pais/editar-pais/6093f8c1b39e7c482c899ffb
Content-Type: application/json

{
    "nomePais": "editado",
    "receitas": []
}

### Cadastrar RECEITA EM PAIS
POST http://localhost:4321/pais/cadastrar-receita/6093f34f5075d121b07ffde4/6093f8d1b39e7c482c899ffc

### REMOVER RECEITA EM PAIS
POST http://localhost:4321/pais/remover-receita/6093f34f5075d121b07ffde4/6093f8d1b39e7c482c899ffc